
package com.fanfan.system.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetPersonnel", targetNamespace = "com.fanfan.system.ws.service")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GetPersonnel {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "com.fanfan.system.ws.service/GetPersonnel/getPersonnelPageRequest", output = "com.fanfan.system.ws.service/GetPersonnel/getPersonnelPageResponse")
    public String getPersonnelPage();

}
